PAAS-1336: fix healthchecks

diff --git a/database/galera_actions.yml b/database/galera_actions.yml
--- a/database/galera_actions.yml
+++ b/database/galera_actions.yml
@@ -73,7 +73,7 @@ actions:
     - cmd [${this}]: |-
         if [ -f /var/lib/mysql/grastate.dat ]; then
           if [ "$(mysql -Ns -e "show global status like 'wsrep_local_state_comment'" | awk '{print $NF}')" != "Synced"  ]; then
-            rc=$? && echo "[ERROR] Galera cluster not synced, exiting" && exit $rc
+            echo "[ERROR] Galera cluster not synced, exiting" 1>&2 && exit 1
           fi
         fi
       user: root
diff --git a/database/mariadb_actions.yml b/database/mariadb_actions.yml
--- a/database/mariadb_actions.yml
+++ b/database/mariadb_actions.yml
@@ -118,10 +118,10 @@ actions:
 
   checkMariadbHealth:
     - cmd [${this}]: |-
-        if ! service mysql status; then
-          rc=$? && echo "[ERROR] Mariadb service is not running, exiting" && exit $rc
+        if ! service mysql status > /dev/null; then
+          echo "[ERROR] Mariadb service is not running, exiting" 1>&2 && exit 1
         fi
         if ! mysqladmin -s processlist 1>/dev/null; then
-          rc=$? && echo "[ERROR] Can't connect to mysql instance, exiting" && exit $rc
+          echo "[ERROR] Can't connect to mysql instance, exiting" 1>&2 && exit 1
         fi
       user: root
