PAAS-1208 better handle problem when talking to vault

diff --git a/utils/ipsec.yml b/utils/ipsec.yml
--- a/utils/ipsec.yml
+++ b/utils/ipsec.yml
@@ -59,8 +59,8 @@ actions:
         END
 
         # auth to vault
-        VAULT_TOKEN=$(curl -s -XPOST $VAULT_CLUSTER_URL/v1/auth/approle/login --data @$payloadfile | jq -r .auth.client_token)
-        if [[ -z "$VAULT_TOKEN" ]] || [[ "$VAULT_TOKEN" == "null" ]]; then
+        VAULT_TOKEN=$(curl -s -XPOST $VAULT_CLUSTER_URL/v1/auth/approle/login --data @$payloadfile | jq -er .auth.client_token)
+        if [ $? -ne 0 ]; then
           echo "[ERROR] Can't generate token (VAULT_TOKEN=$VAULT_TOKEN)" >&2
           exit 1
         fi
@@ -69,20 +69,20 @@ actions:
         # get connection conf file from vault
         conf_tmpfile=$(mktemp)
         curl -s -H "X-Vault-Token: $VAULT_TOKEN" $VAULT_CLUSTER_URL/v1/kv/data/$VAULT_SECRET_PATH \
-          | jq -r .data.data.conf \
+          | jq -er .data.data.conf \
           > $conf_tmpfile
-        if [ ! -s $conf_tmpfile ]; then
-          echo "[ERROR] The ipsec conf is empty" >&2
+        if [ $? -ne 0 ]; then
+          echo "[ERROR] Can't get conf" >&2
           exit 1
         fi
 
         # get connection secret conf from vault
         secret_tmpfile=$(mktemp)
         curl -s -H "X-Vault-Token: $VAULT_TOKEN" $VAULT_CLUSTER_URL/v1/kv/data/$VAULT_SECRET_PATH \
-          | jq -r .data.data.secret \
+          | jq -er .data.data.secret \
           > $secret_tmpfile
-        if [ ! -s $secret_tmpfile ]; then
-          echo "[ERROR] The secret is empty" >&2
+        if [ $? -ne 0 ]; then
+          echo "[ERROR] Can't get secret" >&2
           exit 1
         fi
 
